#!/bin/bash
# Add a new Amadeus user with container-level isolation.
# Usage: ./scripts/add-user.sh <username> [password]
#
# Writes the per-user service to docker-compose.multi.yml (gitignored) so
# usernames never land in the tracked compose file. Also adds nginx route,
# htpasswd entry.
#
# Start: docker compose -f docker-compose.yml -f docker-compose.multi.yml up -d
set -e

USERNAME="${1:?Usage: $0 <username> [password]}"
PASSWORD="${2:-}"
HTPASSWD_FILE="gateway/htpasswd"
ROUTES_FILE="gateway/user-routes.conf"
MULTI_FILE="docker-compose.multi.yml"

# Dedup: abort if user already exists
if [ -f "$MULTI_FILE" ] && grep -q "amadeus-${USERNAME}:" "$MULTI_FILE"; then
  echo "[!] User '${USERNAME}' already exists. Skipping."
  exit 0
fi

# Prompt for password if not given
if [ -z "$PASSWORD" ]; then
  read -s -p "Password for ${USERNAME}: " PASSWORD; echo
fi

mkdir -p gateway

# Add htpasswd entry
HASH=$(openssl passwd -apr1 "$PASSWORD")
echo "${USERNAME}:${HASH}" >> "$HTPASSWD_FILE"

# Add nginx route mapping
echo "    ${USERNAME}    \"amadeus-${USERNAME}:3001\";" >> "$ROUTES_FILE"

# Enable the include in nginx.conf if not already
sed -i.bak 's|# include /etc/nginx/user-routes.conf;|include /etc/nginx/user-routes.conf;|' gateway/nginx.conf 2>/dev/null || true
rm -f gateway/nginx.conf.bak

# Initialize the override file with both section headers the first time.
# Services get inserted before the "volumes:" marker; volume lines after it.
if [ ! -f "$MULTI_FILE" ]; then
  printf '# Generated by add-user.sh — gitignored (contains usernames)\nservices:\nvolumes:\n' > "$MULTI_FILE"
fi

# Insert the per-user service just before the volumes: line
SERVICE_BLOCK=$(cat <<EOF
  amadeus-${USERNAME}:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_AUTH: "false"
    restart: unless-stopped
    container_name: amadeus-${USERNAME}
    volumes:
      - user-data-${USERNAME}:/home/agent
    environment:
      - DISABLE_AUTOUPDATER=1
      - WORKSPACES_ROOT=/home/agent/workspace
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      lightrag:
        condition: service_healthy
EOF
)
# Use a temp file: awk splits at "volumes:", inserting the service before it
# and the volume declaration after it.
awk -v svc="$SERVICE_BLOCK" -v vol="  user-data-${USERNAME}:" '
  /^volumes:/ { print svc; print; print vol; next }
  { print }
' "$MULTI_FILE" > "${MULTI_FILE}.tmp" && mv "${MULTI_FILE}.tmp" "$MULTI_FILE"

echo ""
echo "[+] User '${USERNAME}' added"
echo "    Data volume: user-data-${USERNAME}"
echo "    Container: amadeus-${USERNAME}"
echo ""
echo "Start multi-user mode:"
echo "  docker compose -f docker-compose.yml -f docker-compose.multi.yml up -d"
echo ""
echo "Access: http://localhost:3001 (login as ${USERNAME})"
