#!/bin/bash
# Add a new Amadeus user (container-level isolation)
# Usage: ./scripts/add-user.sh <username> [port]
#
# Creates a workspace directory and appends a new service to docker-compose.users.yml

set -e

USERNAME="${1:?Usage: $0 <username> [port]}"
PORT="${2:-}"
WORKSPACE_ROOT="${WORKSPACE_ROOT:-./workspaces}"
COMPOSE_FILE="docker-compose.users.yml"

# Auto-assign port if not given (3001 + user count)
if [ -z "$PORT" ]; then
  EXISTING=$(grep -c "container_name:" "$COMPOSE_FILE" 2>/dev/null || echo 0)
  PORT=$((3001 + EXISTING))
fi

# Create workspace
mkdir -p "${WORKSPACE_ROOT}/${USERNAME}"
echo "[+] Workspace: ${WORKSPACE_ROOT}/${USERNAME}"

# Create compose override file if it doesn't exist
if [ ! -f "$COMPOSE_FILE" ]; then
  cat > "$COMPOSE_FILE" << 'HEADER'
# Auto-generated by add-user.sh — one service per user
services:
HEADER
fi

# Append user service
cat >> "$COMPOSE_FILE" << EOF

  amadeus-${USERNAME}:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: amadeus-${USERNAME}
    ports:
      - "127.0.0.1:${PORT}:3001"
    volumes:
      - claude-data-${USERNAME}:/home/agent/.claude
      - ${WORKSPACE_ROOT}/${USERNAME}:/home/agent/workspace
    environment:
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY:-}
      - CLAUDE_CODE_OAUTH_TOKEN=\${CLAUDE_CODE_OAUTH_TOKEN:-}
      - AWS_PROFILE=\${AWS_PROFILE:-}
      - AWS_REGION=\${AWS_REGION:-}
      - AWS_ACCESS_KEY_ID=\${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=\${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=\${AWS_SESSION_TOKEN:-}
      - DISABLE_AUTOUPDATER=1
      - WORKSPACES_ROOT=/home/agent/workspace
      - VITE_IS_PLATFORM=true
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
EOF

# Append volume if not already declared
if ! grep -q "claude-data-${USERNAME}:" "$COMPOSE_FILE"; then
  # Check if volumes section exists
  if ! grep -q "^volumes:" "$COMPOSE_FILE"; then
    echo "" >> "$COMPOSE_FILE"
    echo "volumes:" >> "$COMPOSE_FILE"
  fi
  echo "  claude-data-${USERNAME}:" >> "$COMPOSE_FILE"
fi

echo "[+] Added service: amadeus-${USERNAME} on port ${PORT}"
echo ""
echo "Start with:"
echo "  docker compose -f docker-compose.users.yml up -d amadeus-${USERNAME}"
echo ""
echo "Access: http://localhost:${PORT}"
