#!/bin/bash
# Add a multi-user Amadeus user.
# Usage: ./scripts/add-user.sh <username> [password]
#
# Two things happen:
#   1. Register the account in the auth-gateway (shared user DB) — this is what
#      the login page authenticates against and what the cookie identifies.
#   2. Write a per-user backend service to docker-compose.multi.yml (gitignored,
#      contains usernames). The nginx gateway routes amadeus-<username> by the
#      username in the auth cookie; backends run in platform mode (no login of
#      their own) and are never published on the host.
#
# The auth-gateway must be running before this script (it registers over HTTP):
#   docker compose up -d auth-gateway
#
# Then, after adding users:
#   docker compose -f docker-compose.yml -f docker-compose.multi.yml up -d
set -e

USERNAME="${1:?Usage: $0 <username> [password]}"
PASSWORD="${2:-}"
MULTI_FILE="docker-compose.multi.yml"
AUTH_URL="${AMADEUS_AUTH_URL:-http://localhost:3001}"

# Dedup: abort if the backend service already exists
if [ -f "$MULTI_FILE" ] && grep -q "amadeus-${USERNAME}:" "$MULTI_FILE"; then
  echo "[!] User '${USERNAME}' already exists. Skipping."
  exit 0
fi

# Prompt for password if not given
if [ -z "$PASSWORD" ]; then
  read -s -p "Password for ${USERNAME}: " PASSWORD; echo
fi

# 1. Register the account in the auth-gateway's shared user DB.
echo "[*] Registering '${USERNAME}' with the auth-gateway at ${AUTH_URL} ..."
HTTP_CODE=$(curl -s -o /tmp/add-user-resp.$$ -w "%{http_code}" \
  -X POST "${AUTH_URL}/api/auth/register" \
  -H 'Content-Type: application/json' \
  -d "{\"username\":$(printf '%s' "$USERNAME" | jq -R .),\"password\":$(printf '%s' "$PASSWORD" | jq -R .)}") || {
    echo "[!] Could not reach the auth-gateway. Is it running? (docker compose up -d auth-gateway)"
    exit 1
  }
if [ "$HTTP_CODE" != "200" ]; then
  echo "[!] Registration failed (HTTP $HTTP_CODE): $(cat /tmp/add-user-resp.$$)"
  rm -f /tmp/add-user-resp.$$
  exit 1
fi
rm -f /tmp/add-user-resp.$$

# 2. Write the per-user backend service (platform mode, shared secret, no ports).
if [ ! -f "$MULTI_FILE" ]; then
  printf '# Generated by add-user.sh — gitignored (contains usernames)\nservices:\nvolumes:\n' > "$MULTI_FILE"
fi

SERVICE_BLOCK=$(cat <<EOF
  amadeus-${USERNAME}:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_AUTH: "true"
    restart: unless-stopped
    container_name: amadeus-${USERNAME}
    # No ports: reachable only via the gateway on the compose network.
    expose:
      - "3001"
    volumes:
      - user-data-${USERNAME}:/home/agent
    environment:
      - VITE_IS_PLATFORM=true
      - JWT_SECRET=\${JWT_SECRET:?set JWT_SECRET in .env}
      - LIGHTRAG_URL=http://lightrag:9621
      - DISABLE_AUTOUPDATER=1
      - WORKSPACES_ROOT=/home/agent/workspace
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      lightrag:
        condition: service_healthy
EOF
)
awk -v svc="$SERVICE_BLOCK" -v vol="  user-data-${USERNAME}:" '
  /^volumes:/ { print svc; print; print vol; next }
  { print }
' "$MULTI_FILE" > "${MULTI_FILE}.tmp" && mv "${MULTI_FILE}.tmp" "$MULTI_FILE"

echo ""
echo "[+] User '${USERNAME}' added"
echo "    Container: amadeus-${USERNAME}  (volume: user-data-${USERNAME})"
echo ""
echo "Bring up the backends:"
echo "  docker compose -f docker-compose.yml -f docker-compose.multi.yml up -d"
echo ""
echo "Access: http://localhost:3001  (log in as ${USERNAME})"
