#!/bin/bash
# Manage multi-user Amadeus accounts.
#
#   ./scripts/user.sh add    <username> [password]   register + provision backend
#   ./scripts/user.sh remove <username> [--purge]    tear down backend + account
#   ./scripts/user.sh list                           list users and backend status
#
# Each user gets: an account in the auth-gateway's shared DB, and a per-user
# backend service in docker-compose.multi.yml (gitignored — holds usernames).
# The nginx gateway routes amadeus-<username> by the login cookie; backends run
# in platform mode (no login of their own) and are never published on the host.
#
# add ensures the gateway is up first, so `./scripts/user.sh add alice` is all
# you need on a fresh deployment. (AMADEUS_NO_UP=1 skips starting the backend.)
set -e

# Run from the repo root so relative paths and .env resolve.
cd "$(dirname "$0")/.."

# The multi-user gateway shares JWT_SECRET across the auth-gateway and every
# per-user backend container, so it must come from .env (a DB-generated secret
# would differ per container and break token verification). ADMIN_TOKEN gates
# registration. Generate either if absent so a fresh deployment just works —
# must run BEFORE sourcing .env below so the new values are loaded.
ensure_secret() {
  local key="$1"
  [ -f .env ] || touch .env
  if ! grep -q "^${key}=." .env 2>/dev/null; then
    # Drop any empty "KEY=" line, then append a freshly generated value.
    sed -i.bak "/^${key}=$/d" .env && rm -f .env.bak
    echo "${key}=$(openssl rand -hex 32)" >> .env
    echo "[*] Generated ${key} in .env"
  fi
}
ensure_secret JWT_SECRET
ensure_secret AMADEUS_ADMIN_TOKEN
# .env now holds the deployment's root secret — restrict it to the owner.
[ -f .env ] && chmod 600 .env

# Load .env so AMADEUS_ADMIN_TOKEN / JWT_SECRET are available to curl + compose.
[ -f .env ] && set -a && . ./.env && set +a

MULTI_FILE="docker-compose.multi.yml"
AUTH_URL="${AMADEUS_AUTH_URL:-http://localhost:8888}"
COMPOSE=(docker compose -f docker-compose.yml -f "$MULTI_FILE")
# Matches DATABASE_PATH set for auth-gateway in docker-compose.yml.
AUTH_DB="/home/agent/.amadeus/auth.db"

# The per-user backend file is gitignored (holds usernames), so a fresh clone
# won't have it — but every COMPOSE command references it via -f. Create the
# skeleton up front so `docker compose` never fails with "no such file" before
# cmd_add gets a chance to populate it. `services:`/`volumes:` MUST be `{}` while
# empty: a bare `services:` parses as null and compose rejects it ("services must
# be a mapping"). cmd_add strips the `{}` when it inserts the first real entry.
ensure_multi_file() {
  if [ ! -f "$MULTI_FILE" ] || ! grep -qE '^services:' "$MULTI_FILE" || ! grep -qE '^volumes:' "$MULTI_FILE"; then
    printf '# Generated by user.sh — gitignored (contains usernames)\nservices: {}\nvolumes: {}\n' > "$MULTI_FILE"
    return
  fi
  # Repair a pre-existing skeleton whose anchors are bare (`services:` with no
  # value → null). Only touch an anchor line that has nothing after the colon;
  # a populated `services:` (followed by indented entries) is left untouched.
  sed -i.bak -E 's/^(services|volumes):[[:space:]]*$/\1: {}/' "$MULTI_FILE" && rm -f "${MULTI_FILE}.bak"
}
ensure_multi_file

# Emit a JSON-quoted string (with surrounding quotes) for a shell value, so the
# register payload doesn't depend on `jq` being installed. Escapes backslash,
# double-quote, and control chars — enough for usernames/passwords.
json_string() {
  printf '%s' "$1" | LC_ALL=C awk '
    BEGIN { RS="\0"; ORS=""; printf "\"" }
    {
      gsub(/\\/, "\\\\"); gsub(/"/, "\\\"")
      gsub(/\t/, "\\t"); gsub(/\r/, "\\r"); gsub(/\n/, "\\n")
      printf "%s", $0
    }
    END { printf "\"" }
  '
}

ensure_gateway() {
  if ! curl -s -o /dev/null --max-time 2 "${AUTH_URL}/api/auth/status"; then
    echo "[*] Gateway not responding — starting gateway + auth-gateway ..."
    "${COMPOSE[@]}" up -d --build gateway auth-gateway
    for _ in $(seq 1 30); do
      curl -s -o /dev/null --max-time 2 "${AUTH_URL}/api/auth/status" && break
      sleep 1
    done
  fi
}

cmd_add() {
  local USERNAME="${1:?Usage: user.sh add <username> [password]}"
  local PASSWORD="${2:-}"

  if [ -f "$MULTI_FILE" ] && grep -q "amadeus-${USERNAME}:" "$MULTI_FILE"; then
    echo "[!] User '${USERNAME}' already exists. Skipping."
    exit 0
  fi
  if [ -z "$PASSWORD" ]; then
    read -s -p "Password for ${USERNAME}: " PASSWORD; echo
  fi

  ensure_gateway

  echo "[*] Registering '${USERNAME}' ..."
  local code
  code=$(curl -s -o /tmp/user-resp.$$ -w "%{http_code}" \
    -X POST "${AUTH_URL}/api/auth/register" \
    -H 'Content-Type: application/json' \
    -H "X-Admin-Token: ${AMADEUS_ADMIN_TOKEN:-}" \
    -d "{\"username\":$(json_string "$USERNAME"),\"password\":$(json_string "$PASSWORD")}") || {
      echo "[!] Could not reach the auth-gateway."; exit 1; }
  if [ "$code" != "200" ]; then
    echo "[!] Registration failed (HTTP $code): $(cat /tmp/user-resp.$$)"; rm -f /tmp/user-resp.$$; exit 1
  fi
  rm -f /tmp/user-resp.$$

  # Re-assert the anchors the insert relies on, in case the file was edited.
  ensure_multi_file

  local block
  block=$(cat <<EOF
  amadeus-${USERNAME}:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_AUTH: "true"
    restart: unless-stopped
    # Per-user resource caps so one runaway agent can't starve the host or other
    # users. Plain-compose keys (deploy.resources needs Swarm). Tune AMADEUS_USER_CPUS
    # / AMADEUS_USER_MEM in the environment before \`add\` to override the defaults.
    cpus: "${AMADEUS_USER_CPUS:-6}"
    mem_limit: ${AMADEUS_USER_MEM:-6g}
    memswap_limit: ${AMADEUS_USER_MEM:-6g}
    container_name: amadeus-${USERNAME}
    expose:
      - "3001"
    volumes:
      - user-data-${USERNAME}:/home/agent
    environment:
      - VITE_IS_PLATFORM=true
      - AMADEUS_USER=${USERNAME}
      - JWT_SECRET=\${JWT_SECRET:?set JWT_SECRET in .env}
      - DISABLE_AUTOUPDATER=1
      - WORKSPACES_ROOT=/home/agent/workspace
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
EOF
)
  # Insert the service block before `volumes:` and the named volume after it.
  # Normalize the empty-skeleton `{}` back to a block header on the two anchor
  # lines, otherwise we'd emit `services: {}` followed by block entries (invalid).
  awk -v svc="$block" -v vol="  user-data-${USERNAME}:" '
    /^services:/ { print "services:"; next }
    /^volumes:/  { print svc; print "volumes:"; print vol; next }
    { print }
  ' "$MULTI_FILE" > "${MULTI_FILE}.tmp" && mv "${MULTI_FILE}.tmp" "$MULTI_FILE"

  echo "[+] User '${USERNAME}' added (container amadeus-${USERNAME}, volume user-data-${USERNAME})"

  if [ "${AMADEUS_NO_UP:-}" = "1" ]; then
    echo "Skipped startup (AMADEUS_NO_UP=1). Start later with:"
    echo "  ${COMPOSE[*]} up -d"
  else
    echo "[*] Starting backend amadeus-${USERNAME} ..."
    "${COMPOSE[@]}" up -d --build "amadeus-${USERNAME}"
  fi
  echo ""
  echo "Access: ${AUTH_URL}  (log in as ${USERNAME})"
}

cmd_remove() {
  local USERNAME="${1:?Usage: user.sh remove <username> [--purge]}"
  local PURGE=""
  [ "${2:-}" = "--purge" ] && PURGE=1

  echo "[*] Stopping + removing backend amadeus-${USERNAME} ..."
  docker rm -f "amadeus-${USERNAME}" 2>/dev/null || true

  if [ -n "$PURGE" ]; then
    echo "[*] Purging data volume user-data-${USERNAME} ..."
    # Try both the compose-prefixed and bare volume names.
    docker volume rm "amadeus_user-data-${USERNAME}" "user-data-${USERNAME}" 2>/dev/null || true
  fi

  # Drop this user's service block and volume line from the generated file.
  # The service block is "  amadeus-<user>:" plus its deeper-indented body;
  # skip ends at the next line that is NOT part of that body (indent <= 2),
  # so top-level anchors like "volumes:" are never consumed.
  if [ -f "$MULTI_FILE" ]; then
    awk -v u="  amadeus-${USERNAME}:" -v v="  user-data-${USERNAME}:" '
      $0 == u { skip=1; next }
      skip && $0 !~ /^    / { skip=0 }   # left the 4-space service body
      skip { next }
      $0 == v { next }
      { print }
    ' "$MULTI_FILE" > "${MULTI_FILE}.tmp" && mv "${MULTI_FILE}.tmp" "$MULTI_FILE"
  fi

  # Delete the account from the auth DB (direct — no exposed endpoint).
  echo "[*] Removing account '${USERNAME}' from the auth DB ..."
  docker exec amadeus-auth-gateway-1 sqlite3 "$AUTH_DB" \
    "DELETE FROM users WHERE username = '${USERNAME}';" 2>/dev/null \
    || echo "[!] Could not reach auth DB (auth-gateway not running?) — account row may remain."

  echo "[+] User '${USERNAME}' removed$([ -n "$PURGE" ] && echo ' (data purged)')"
}

cmd_list() {
  echo "=== Accounts (auth DB) ==="
  docker exec amadeus-auth-gateway-1 sqlite3 "$AUTH_DB" \
    "SELECT username FROM users ORDER BY username;" 2>/dev/null \
    || echo "(auth-gateway not running)"
  echo ""
  echo "=== Backend containers ==="
  # Only per-user backends: exclude infra (gateway/auth) and the
  # separate dev stack (amadeus-dev-*).
  docker ps -a --filter "name=amadeus-" --format '{{.Names}}\t{{.Status}}' \
    | grep -vE "^amadeus-(gateway|auth-gateway|dev-)" || echo "(none)"
}

case "${1:-}" in
  add)    shift; cmd_add "$@" ;;
  remove) shift; cmd_remove "$@" ;;
  list)   shift; cmd_list "$@" ;;
  *) echo "Usage: $0 {add|remove|list} ..."; exit 1 ;;
esac
