#!/bin/bash
# Manage multi-user Amadeus accounts.
#
#   ./scripts/user.sh add    <username> [password]   register + provision backend
#   ./scripts/user.sh remove <username> [--purge]    tear down backend + account
#   ./scripts/user.sh list                           list users and backend status
#
# Each user gets: an account in the auth-gateway's shared DB, and a per-user
# backend service in docker-compose.multi.yml (gitignored — holds usernames).
# The nginx gateway routes amadeus-<username> by the login cookie; backends run
# in platform mode (no login of their own) and are never published on the host.
#
# add ensures the gateway is up first, so `./scripts/user.sh add alice` is all
# you need on a fresh deployment. (AMADEUS_NO_UP=1 skips starting the backend.)
set -e

# Run from the repo root so relative paths and .env resolve.
cd "$(dirname "$0")/.."
# Load .env for AMADEUS_ADMIN_TOKEN (needed to authorize registration).
[ -f .env ] && set -a && . ./.env && set +a

MULTI_FILE="docker-compose.multi.yml"
AUTH_URL="${AMADEUS_AUTH_URL:-http://localhost:3001}"
COMPOSE=(docker compose -f docker-compose.yml -f "$MULTI_FILE")
# Matches DATABASE_PATH set for auth-gateway in docker-compose.yml.
AUTH_DB="/home/agent/.cloudcli/auth.db"

ensure_gateway() {
  if ! curl -s -o /dev/null --max-time 2 "${AUTH_URL}/api/auth/status"; then
    echo "[*] Gateway not responding — starting gateway + auth-gateway ..."
    docker compose up -d --build gateway auth-gateway lightrag
    for _ in $(seq 1 30); do
      curl -s -o /dev/null --max-time 2 "${AUTH_URL}/api/auth/status" && break
      sleep 1
    done
  fi
}

cmd_add() {
  local USERNAME="${1:?Usage: user.sh add <username> [password]}"
  local PASSWORD="${2:-}"

  if [ -f "$MULTI_FILE" ] && grep -q "amadeus-${USERNAME}:" "$MULTI_FILE"; then
    echo "[!] User '${USERNAME}' already exists. Skipping."
    exit 0
  fi
  if [ -z "$PASSWORD" ]; then
    read -s -p "Password for ${USERNAME}: " PASSWORD; echo
  fi

  ensure_gateway

  echo "[*] Registering '${USERNAME}' ..."
  local code
  code=$(curl -s -o /tmp/user-resp.$$ -w "%{http_code}" \
    -X POST "${AUTH_URL}/api/auth/register" \
    -H 'Content-Type: application/json' \
    -H "X-Admin-Token: ${AMADEUS_ADMIN_TOKEN:-}" \
    -d "{\"username\":$(printf '%s' "$USERNAME" | jq -R .),\"password\":$(printf '%s' "$PASSWORD" | jq -R .)}") || {
      echo "[!] Could not reach the auth-gateway."; exit 1; }
  if [ "$code" != "200" ]; then
    echo "[!] Registration failed (HTTP $code): $(cat /tmp/user-resp.$$)"; rm -f /tmp/user-resp.$$; exit 1
  fi
  rm -f /tmp/user-resp.$$

  # Ensure the file has the two anchors the insert relies on ("services:" and
  # a trailing "volumes:"). Recreate if missing/corrupt so add never no-ops.
  if [ ! -f "$MULTI_FILE" ] || ! grep -q '^services:' "$MULTI_FILE" || ! grep -q '^volumes:' "$MULTI_FILE"; then
    printf '# Generated by user.sh — gitignored (contains usernames)\nservices:\nvolumes:\n' > "$MULTI_FILE"
  fi

  local block
  block=$(cat <<EOF
  amadeus-${USERNAME}:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_AUTH: "true"
    restart: unless-stopped
    container_name: amadeus-${USERNAME}
    expose:
      - "3001"
    volumes:
      - user-data-${USERNAME}:/home/agent
    environment:
      - VITE_IS_PLATFORM=true
      - AMADEUS_USER=${USERNAME}
      - JWT_SECRET=\${JWT_SECRET:?set JWT_SECRET in .env}
      - LIGHTRAG_URL=http://lightrag:9621
      - DISABLE_AUTOUPDATER=1
      - WORKSPACES_ROOT=/home/agent/workspace
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      lightrag:
        condition: service_healthy
EOF
)
  awk -v svc="$block" -v vol="  user-data-${USERNAME}:" '
    /^volumes:/ { print svc; print; print vol; next } { print }
  ' "$MULTI_FILE" > "${MULTI_FILE}.tmp" && mv "${MULTI_FILE}.tmp" "$MULTI_FILE"

  echo "[+] User '${USERNAME}' added (container amadeus-${USERNAME}, volume user-data-${USERNAME})"

  if [ "${AMADEUS_NO_UP:-}" = "1" ]; then
    echo "Skipped startup (AMADEUS_NO_UP=1). Start later with:"
    echo "  ${COMPOSE[*]} up -d"
  else
    echo "[*] Starting backend amadeus-${USERNAME} ..."
    "${COMPOSE[@]}" up -d --build "amadeus-${USERNAME}"
  fi
  echo ""
  echo "Access: http://localhost:3001  (log in as ${USERNAME})"
}

cmd_remove() {
  local USERNAME="${1:?Usage: user.sh remove <username> [--purge]}"
  local PURGE=""
  [ "${2:-}" = "--purge" ] && PURGE=1

  echo "[*] Stopping + removing backend amadeus-${USERNAME} ..."
  docker rm -f "amadeus-${USERNAME}" 2>/dev/null || true

  if [ -n "$PURGE" ]; then
    echo "[*] Purging data volume user-data-${USERNAME} ..."
    # Try both the compose-prefixed and bare volume names.
    docker volume rm "amadeus_user-data-${USERNAME}" "user-data-${USERNAME}" 2>/dev/null || true
  fi

  # Drop this user's service block and volume line from the generated file.
  # The service block is "  amadeus-<user>:" plus its deeper-indented body;
  # skip ends at the next line that is NOT part of that body (indent <= 2),
  # so top-level anchors like "volumes:" are never consumed.
  if [ -f "$MULTI_FILE" ]; then
    awk -v u="  amadeus-${USERNAME}:" -v v="  user-data-${USERNAME}:" '
      $0 == u { skip=1; next }
      skip && $0 !~ /^    / { skip=0 }   # left the 4-space service body
      skip { next }
      $0 == v { next }
      { print }
    ' "$MULTI_FILE" > "${MULTI_FILE}.tmp" && mv "${MULTI_FILE}.tmp" "$MULTI_FILE"
  fi

  # Delete the account from the auth DB (direct — no exposed endpoint).
  echo "[*] Removing account '${USERNAME}' from the auth DB ..."
  docker exec amadeus-auth-gateway-1 sqlite3 "$AUTH_DB" \
    "DELETE FROM users WHERE username = '${USERNAME}';" 2>/dev/null \
    || echo "[!] Could not reach auth DB (auth-gateway not running?) — account row may remain."

  echo "[+] User '${USERNAME}' removed$([ -n "$PURGE" ] && echo ' (data purged)')"
}

cmd_list() {
  echo "=== Accounts (auth DB) ==="
  docker exec amadeus-auth-gateway-1 sqlite3 "$AUTH_DB" \
    "SELECT username FROM users ORDER BY username;" 2>/dev/null \
    || echo "(auth-gateway not running)"
  echo ""
  echo "=== Backend containers ==="
  # Only per-user backends: exclude infra (gateway/auth/lightrag) and the
  # separate dev stack (amadeus-dev-*).
  docker ps -a --filter "name=amadeus-" --format '{{.Names}}\t{{.Status}}' \
    | grep -vE "^amadeus-(gateway|auth-gateway|lightrag|dev-)" || echo "(none)"
}

case "${1:-}" in
  add)    shift; cmd_add "$@" ;;
  remove) shift; cmd_remove "$@" ;;
  list)   shift; cmd_list "$@" ;;
  *) echo "Usage: $0 {add|remove|list} ..."; exit 1 ;;
esac
